/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabaseCrud;

import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.ResourceBundle;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author attiac
 */
public class DatabaseCrudJava extends javax.swing.JFrame {

    private DefaultTableModel dataModel;
    private DefaultTableModel dataModelHome;
    private Queries db = new Queries();
    ResourceBundle bundle = ResourceBundle.getBundle("domaine.properties.config");
    String nomBddDatabase = bundle.getString("bdd.name");

    /**
     * Creates new form Fezzouille
     */
    public DatabaseCrudJava() throws IOException, SQLException {

        dataModel = new DefaultTableModel();
        dataModelHome = new DefaultTableModel();
        db.miseEnPlace();
        initComponents();
        getTable();

        EditorPaneNote.setContentType("text/html");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        buttonUpdate = new javax.swing.JButton();
        buttonNew = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pParametre = new javax.swing.JPanel();
        textEmployeeNaiss = new javax.swing.JTextField();
        textEmployeeNumTrav = new javax.swing.JTextField();
        textEmployeeNbMobile = new javax.swing.JTextField();
        textEmployeeEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textEmployeNb = new javax.swing.JTextField();
        textEmployeNom = new javax.swing.JTextField();
        textEmployeeAdd = new javax.swing.JTextField();
        textState = new javax.swing.JTextField();
        textEmployeeSuburb = new javax.swing.JTextField();
        textEmployeePostCode = new javax.swing.JTextField();
        textEmployeeNbNumMais = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textFindPersonne = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textNomBdD = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        buttonEnregistrerFichier = new javax.swing.JButton();
        buttonEnvoieReq = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textRequeteSQL = new javax.swing.JEditorPane();
        jLabel19 = new javax.swing.JLabel();
        textNameTable = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        buttonReqDelete = new javax.swing.JButton();
        buttonReqSelect = new javax.swing.JButton();
        buttonReqUpdate = new javax.swing.JButton();
        buttonReqInsert = new javax.swing.JButton();
        buttonReqSelectAll = new javax.swing.JButton();
        buttonDefault = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        openFile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditorPaneNote = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database Application");

        this.jTable1.setModel(this.dataModel);
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonNew.setText("New");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        this.jTable2.setModel(this.dataModelHome);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        pParametre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textEmployeeNaiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeNaissMouseClicked(evt);
            }
        });
        textEmployeeNaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeNaissActionPerformed(evt);
            }
        });

        textEmployeeNumTrav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeNumTravMouseClicked(evt);
            }
        });
        textEmployeeNumTrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeNumTravActionPerformed(evt);
            }
        });

        textEmployeeNbMobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeNbMobileMouseClicked(evt);
            }
        });
        textEmployeeNbMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeNbMobileActionPerformed(evt);
            }
        });

        textEmployeeEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeEmailMouseClicked(evt);
            }
        });
        textEmployeeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeEmailActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee No");

        jLabel2.setText("Name");

        jLabel3.setText("Suburb");

        jLabel4.setText("Adress");

        jLabel5.setText("State");

        jLabel6.setText("PostCode");

        jLabel7.setText("Date Of Birth");

        jLabel8.setText("Home Phone");

        jLabel9.setText("Work Phone");

        jLabel10.setText("Mobile");

        jLabel11.setText("Email");

        textEmployeNb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeNbMouseClicked(evt);
            }
        });
        textEmployeNb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeNbActionPerformed(evt);
            }
        });

        textEmployeNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeNomMouseClicked(evt);
            }
        });
        textEmployeNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeNomActionPerformed(evt);
            }
        });

        textEmployeeAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeAddMouseClicked(evt);
            }
        });

        textState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textStateMouseClicked(evt);
            }
        });

        textEmployeeSuburb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeSuburbMouseClicked(evt);
            }
        });

        textEmployeePostCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeePostCodeMouseClicked(evt);
            }
        });

        textEmployeeNbNumMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEmployeeNbNumMaisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textEmployeeNbNumMaisMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pParametreLayout = new javax.swing.GroupLayout(pParametre);
        pParametre.setLayout(pParametreLayout);
        pParametreLayout.setHorizontalGroup(
            pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pParametreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textEmployeNom)
                    .addComponent(textEmployeNb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmployeeAdd)
                    .addComponent(textEmployeePostCode)
                    .addComponent(textState)
                    .addComponent(textEmployeeEmail)
                    .addComponent(textEmployeeSuburb)
                    .addComponent(textEmployeeNumTrav)
                    .addComponent(textEmployeeNbMobile)
                    .addComponent(textEmployeeNbNumMais)
                    .addComponent(textEmployeeNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pParametreLayout.setVerticalGroup(
            pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pParametreLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textEmployeNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textEmployeNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textEmployeeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textEmployeeSuburb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textEmployeePostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textEmployeeNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textEmployeeNbNumMais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textEmployeeNumTrav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textEmployeeNbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel21.setText("Cliquez sur l'une des cases pour accéder à toutes les informations de l'employé : ");

        textFindPersonne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFindPersonneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFindPersonneKeyReleased(evt);
            }
        });

        jLabel73.setText("Rechercher personne ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pParametre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel73)
                                        .addGap(46, 46, 46)
                                        .addComponent(textFindPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73)
                            .addComponent(textFindPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                    .addComponent(pParametre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("General", jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Database");

        jLabel13.setText("Query");

        jLabel14.setText("Report File");

        textNomBdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomBdDActionPerformed(evt);
            }
        });

        buttonEnregistrerFichier.setText("Report File");
        buttonEnregistrerFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnregistrerFichierActionPerformed(evt);
            }
        });

        buttonEnvoieReq.setText("Submit Query");
        buttonEnvoieReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnvoieReqActionPerformed(evt);
            }
        });

        textRequeteSQL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textRequeteSQL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnvoieReqSQLDev(evt);
            }
        });
        jScrollPane4.setViewportView(textRequeteSQL);

        jLabel19.setText("Table");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        this.jTable1.setModel(this.dataModel);
        jScrollPane5.setViewportView(jTable1);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonReqDelete.setText("DELETE");
        buttonReqDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReqDeleteActionPerformed(evt);
            }
        });

        buttonReqSelect.setText("SELECT");
        buttonReqSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReqSelectActionPerformed(evt);
            }
        });

        buttonReqUpdate.setText("UPDATE");
        buttonReqUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReqUpdateActionPerformed(evt);
            }
        });

        buttonReqInsert.setText("INSERT");
        buttonReqInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReqInsertActionPerformed(evt);
            }
        });

        buttonReqSelectAll.setText("SELECT *");
        buttonReqSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReqSelectAllActionPerformed(evt);
            }
        });

        buttonDefault.setText("Default");
        buttonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDefaultActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Raccourcis : ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buttonReqSelectAll)
                        .addGap(61, 61, 61)
                        .addComponent(buttonReqInsert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonReqUpdate)
                            .addComponent(buttonReqSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDefault)
                            .addComponent(buttonReqDelete))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReqSelect)
                    .addComponent(buttonDefault))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReqUpdate)
                    .addComponent(buttonReqDelete))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReqSelectAll)
                    .addComponent(buttonReqInsert))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        openFile.setText("Open HTML File");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(buttonEnvoieReq)
                                .addGap(167, 167, 167)
                                .addComponent(buttonEnregistrerFichier)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(textNomBdD, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19)
                                        .addGap(52, 52, 52)
                                        .addComponent(textNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(22, 22, 22)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textNomBdD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(openFile)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEnvoieReq)
                    .addComponent(buttonEnregistrerFichier))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane2.addTab("Queries", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Logiciel créé par Christian ATTIA, étudiant en informatique.");

        jLabel16.setText("Version du logiciel : 1.0");

        jLabel17.setText("Prix du logiciel : 500e Sauf pour Mr Fezzani (gratuit si il utilise le calculateur de note)");

        jScrollPane1.setViewportView(EditorPaneNote);

        jButton1.setText("Calculer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Calculateur de note : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel18)))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(43, 43, 43)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Author", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("General");
        jTabbedPane2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        Employee Emploi = new Employee(Integer.parseInt(textEmployeNb.getText()), textEmployeNom.getText(), textEmployeeAdd.getText(), textEmployeeSuburb.getText(), textState.getText(), Integer.parseInt(textEmployeePostCode.getText()), textEmployeeNaiss.getText(), Integer.parseInt(textEmployeeNbNumMais.getText()), Integer.parseInt(textEmployeeNumTrav.getText()), Integer.parseInt(textEmployeeNbMobile.getText()), textEmployeeEmail.getText());
        Queries Update = new Queries();
        try {
            Update.update(Emploi);
            getTable();
            System.out.println("reusi");
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("testecher");
        } catch (IOException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        Employee Emploi = new Employee(Integer.parseInt(textEmployeNb.getText()), textEmployeNom.getText(), textEmployeeAdd.getText(), textEmployeeSuburb.getText(), textState.getText(), Integer.parseInt(textEmployeePostCode.getText()), textEmployeeNaiss.getText(), Integer.parseInt(textEmployeeNbNumMais.getText()), Integer.parseInt(textEmployeeNumTrav.getText()), Integer.parseInt(textEmployeeNbMobile.getText()), textEmployeeEmail.getText());
        Queries Delete = new Queries();
        try {
            Delete.delete(Emploi);
            getTable();
            System.out.println("reusi");
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("testecher");
        } catch (IOException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void textEmployeeNumTravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeNumTravActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeNumTravActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed

        try {
            getTable();

        } catch (IOException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Component component : pParametre.getComponents()) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }

        }

    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        boolean acces = true;
        for (Component component : pParametre.getComponents()) {
            if (component instanceof JTextField && ((JTextField) component).getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Un paramètre est manquant");
                acces = false;
                break;
            }
        }
        if (textEmployeeEmail.getText().contains("@") == false) {
            JOptionPane.showMessageDialog(null, "Veuillez ecrire un email correct ! ");
            acces = false;
        }

        if (acces == true) {
            Employee Emploi = new Employee(Integer.parseInt(textEmployeNb.getText()), textEmployeNom.getText(), textEmployeeAdd.getText(), textEmployeeSuburb.getText(), textState.getText(), Integer.parseInt(textEmployeePostCode.getText()), textEmployeeNaiss.getText(), Integer.parseInt(textEmployeeNbNumMais.getText()), Integer.parseInt(textEmployeeNumTrav.getText()), Integer.parseInt(textEmployeeNbMobile.getText()), textEmployeeEmail.getText());
            System.out.println(Emploi);
            Queries Ajout = new Queries();

            try {
                Ajout.add(Emploi);

                getTable();
            } catch (SQLException ex) {
                Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_buttonAddActionPerformed

    private void textEmployeNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeNomActionPerformed

    private void textEmployeeNaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeNaissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeNaissActionPerformed

    private void textEmployeeNbMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeNbMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeNbMobileActionPerformed

    private void textEmployeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeEmailActionPerformed
    public void getTable() throws IOException {
        try {
            Queries getTable = new Queries();
            getTable.randomRequest(nomBddDatabase, "select numEmploye, nomEmploye from employe", "");

            //  dataModelHome.hi(ERROR);
            dataModelHome.setDataVector(getTable.getDatatab(), getTable.getColname());
            jTable2.removeColumn(jTable2.getColumnModel().getColumn(0));
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void verif() {
        if (textNomBdD.getText().length() == 0 || textNameTable.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Remplissez le nom de la base de donnée/table");
        }
    }

    public void erreur() {
        JOptionPane.showMessageDialog(null, "Une erreur SQL a été réalisée, vérifiez vos mots de passe/identifiant, nom de base de donnée.. Si l'erreur persite contactez le développeur");
    }
    private void buttonEnvoieReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnvoieReqActionPerformed

        try {

            db.randomRequest(textNomBdD.getText(), textRequeteSQL.getText(), textNameTable.getText());
            String[] columnNames = db.getColname();
            Object[][] data = db.getDatatab();
            dataModel.setDataVector(db.getDatatab(), db.getColname());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonEnvoieReqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        EditorPaneNote.setText("");
        final ScheduledExecutorService Minuteur = Executors.newSingleThreadScheduledExecutor();

        Minuteur.scheduleWithFixedDelay(new Runnable() {
            int i = 0;

            @Override
            public void run() {
                jProgressBar1.setValue(i);
                System.out.println(jProgressBar1.getValue());
                i++;
                if (jProgressBar1.getValue() == 100) {
                    EditorPaneNote.setText("<table border=\"1\">"
                            + "             <tr>"
                            + "             <td style=\"background-color: yellow\" >Performance logiciel(2 points)</td style=\"background-color: yellow\" ><td style=\"background-color: yellow\" >Beauté du Code (2 points)</td><td style=\"background-color: yellow\" >Sympathie de l'élève (16 points)</td><td style=\"background-color: yellow\" >Total (20 points)</td>"
                            + "             </tr>"
                            + "             <tr>"
                            + "             <td>2/2</td><td>3/2</td><td>20/16</td><td>25/20</td>"
                            + "             </tr>");
                    Minuteur.shutdown();
                }
            }

        }, 0, 10, TimeUnit.MILLISECONDS);


        /*
        EditorPaneNote.setText(EditorPaneNote.getText() + "<table border=\"1\">");
        EditorPaneNote.setText(EditorPaneNote.getText() + "<tr>");
        EditorPaneNote.setText(EditorPaneNote.getText() + "<td>Performance logiciel(2 points)</td>"
                + "             <td>Beauté du Code (2 points)</td>"
                + "             <td>Sympathie de l'élève (16 points)</td>"
                + "             <td>Total (20points)</td>");
        EditorPaneNote.setText(EditorPaneNote.getText() + "</tr>");
        EditorPaneNote.setText(EditorPaneNote.getText() + "<td>2/2</td>"
                + "             <td>3/2</td>"
                + "             <td>20/16</td>"
                + "             <td>Total : 25/20</td>");
        EditorPaneNote.setText(EditorPaneNote.getText() + "</table>");
         */
        System.out.println(EditorPaneNote.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonReqSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReqSelectActionPerformed
        verif(); // TODO add your handling code here:
        Queries query = new Queries();
        try {
            textRequeteSQL.setText(query.reqSelect(textNomBdD.getText(), textNameTable.getText()));

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            erreur();
        }
    }//GEN-LAST:event_buttonReqSelectActionPerformed

    private void buttonReqUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReqUpdateActionPerformed
        verif();
        Queries query = new Queries();
        try {
            textRequeteSQL.setText(query.reqUpdate(textNomBdD.getText(), textNameTable.getText()));

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            erreur();
        }
    }//GEN-LAST:event_buttonReqUpdateActionPerformed

    private void buttonReqInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReqInsertActionPerformed
        verif();
        Queries query = new Queries();

        try {
            textRequeteSQL.setText(query.reqInsert(textNomBdD.getText(), textNameTable.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            erreur();
        }
    }//GEN-LAST:event_buttonReqInsertActionPerformed

    private void buttonReqDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReqDeleteActionPerformed
        verif();
        Queries query = new Queries();
        textRequeteSQL.setText(query.reqDelete(textNameTable.getText()));
    }//GEN-LAST:event_buttonReqDeleteActionPerformed

    private void buttonReqSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReqSelectAllActionPerformed
        verif();
        Queries query = new Queries();
        try {
            textRequeteSQL.setText(query.reqSelectAll(textNameTable.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonReqSelectAllActionPerformed

    private void buttonDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDefaultActionPerformed

        textNomBdD.setText(nomBddDatabase);
        textNameTable.setText("employe");
        textRequeteSQL.setText("SELECT * FROM employe");
    }//GEN-LAST:event_buttonDefaultActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int viewRow = jTable2.getSelectedRow();
        int modelRow = jTable2.convertRowIndexToModel(viewRow);

        System.out.println(Integer.parseInt(jTable2.getModel().getValueAt(modelRow, jTable2.getSelectedColumn()).toString()));
        Employee emploiTab = new Employee(Integer.parseInt(jTable2.getModel().getValueAt(modelRow, jTable2.getSelectedColumn()).toString()));
        Queries findTab = new Queries();
        HashMap<String, String> map = new HashMap();
        try {

            map = findTab.retrieve(emploiTab, "NumEmploye");

            textEmployeNb.setText(map.get("NumEmploye"));
            textEmployeNom.setText(map.get("nomEmploye"));
            textEmployeeAdd.setText(map.get("addressEmploye"));
            textEmployeeEmail.setText(map.get("EmailEmploye"));
            textEmployeeNaiss.setText(map.get("AnneNaissEmploy"));
            textEmployeeNbMobile.setText(map.get("numPortabEmploye"));
            textEmployeeNbNumMais.setText(map.get("NumMaisEmploye"));
            textEmployeeNumTrav.setText(map.get("numTravEmploye"));
            textState.setText(map.get("StateEmploye"));
            textEmployeeSuburb.setText(map.get("SuburbEmploye"));
            textEmployeePostCode.setText(map.get("CodePostEmploye"));
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void buttonEnregistrerFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnregistrerFichierActionPerformed

        try {

            jTextField14.setText(db.generateHtmlFile(db.getErr()));
        } catch (IOException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println();
    }//GEN-LAST:event_buttonEnregistrerFichierActionPerformed

    private void EnvoieReqSQLDev(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnvoieReqSQLDev
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && evt.isControlDown()) {
            try {

                db.randomRequest(textNomBdD.getText(), textRequeteSQL.getText(), textNameTable.getText());
                String[] columnNames = db.getColname();
                Object[][] data = db.getDatatab();
                JTable table = new JTable(data, columnNames);
                dataModel.setDataVector(db.getDatatab(), db.getColname());

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } catch (IOException ex) {
                Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_EnvoieReqSQLDev

    private void textEmployeNbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeNbActionPerformed

    }//GEN-LAST:event_textEmployeNbActionPerformed

    private void textEmployeNbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeNbMouseClicked
        // TODO add your handling code here:
        textEmployeNb.selectAll();
    }//GEN-LAST:event_textEmployeNbMouseClicked

    private void textEmployeNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeNomMouseClicked
        // TODO add your handling code here:
        textEmployeNom.selectAll();
    }//GEN-LAST:event_textEmployeNomMouseClicked

    private void textEmployeeAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeAddMouseClicked
        // TODO add your handling code here:
        textEmployeeAdd.selectAll();
    }//GEN-LAST:event_textEmployeeAddMouseClicked

    private void textEmployeeSuburbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeSuburbMouseClicked
        // TODO add your handling code here:
        textEmployeeSuburb.selectAll();
    }//GEN-LAST:event_textEmployeeSuburbMouseClicked

    private void textStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textStateMouseClicked
        // TODO add your handling code here:
        textState.selectAll();
    }//GEN-LAST:event_textStateMouseClicked

    private void textEmployeePostCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeePostCodeMouseClicked
        // TODO add your handling code here:
        textEmployeePostCode.selectAll();
    }//GEN-LAST:event_textEmployeePostCodeMouseClicked

    private void textEmployeeNaissMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeNaissMouseClicked
        // TODO add your handling code here:
        textEmployeeNaiss.selectAll();
    }//GEN-LAST:event_textEmployeeNaissMouseClicked

    private void textEmployeeNbNumMaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeNbNumMaisMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeNbNumMaisMouseEntered

    private void textEmployeeNbNumMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeNbNumMaisMouseClicked
        // TODO add your handling code here:
        textEmployeeNbNumMais.selectAll();
    }//GEN-LAST:event_textEmployeeNbNumMaisMouseClicked

    private void textEmployeeNumTravMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeNumTravMouseClicked
        // TODO add your handling code here:
        textEmployeeNumTrav.selectAll();
    }//GEN-LAST:event_textEmployeeNumTravMouseClicked

    private void textEmployeeNbMobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeNbMobileMouseClicked
        // TODO add your handling code here:
        textEmployeeNbMobile.selectAll();
    }//GEN-LAST:event_textEmployeeNbMobileMouseClicked

    private void textEmployeeEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEmployeeEmailMouseClicked
        // TODO add your handling code here:
        textEmployeeEmail.selectAll();
    }//GEN-LAST:event_textEmployeeEmailMouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        try {
            // TODO add your handling code here:
            db.miseEnPlace();
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        // TODO add your handling code here:
        createFile MyFile = new createFile();
        try {
            MyFile.Open(jTextField14.getText());
        } catch (IOException ex) {
            Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_openFileActionPerformed

    private void textNomBdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomBdDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomBdDActionPerformed

    private void textFindPersonneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindPersonneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFindPersonneKeyPressed
    private void filter(String query, DefaultTableModel dm, JTable jtable) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        jtable.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(query));

    }
    private void textFindPersonneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindPersonneKeyReleased
        // TODO add your handling code here:
        String query = textFindPersonne.getText();
        filter(query, dataModelHome, jTable2);
    }//GEN-LAST:event_textFindPersonneKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseCrudJava.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseCrudJava.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseCrudJava.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseCrudJava.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new DatabaseCrudJava().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DatabaseCrudJava.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane EditorPaneNote;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDefault;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEnregistrerFichier;
    private javax.swing.JButton buttonEnvoieReq;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonReqDelete;
    private javax.swing.JButton buttonReqInsert;
    private javax.swing.JButton buttonReqSelect;
    private javax.swing.JButton buttonReqSelectAll;
    private javax.swing.JButton buttonReqUpdate;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JButton openFile;
    private javax.swing.JPanel pParametre;
    private javax.swing.JTextField textEmployeNb;
    private javax.swing.JTextField textEmployeNom;
    private javax.swing.JTextField textEmployeeAdd;
    private javax.swing.JTextField textEmployeeEmail;
    private javax.swing.JTextField textEmployeeNaiss;
    private javax.swing.JTextField textEmployeeNbMobile;
    private javax.swing.JTextField textEmployeeNbNumMais;
    private javax.swing.JTextField textEmployeeNumTrav;
    private javax.swing.JTextField textEmployeePostCode;
    private javax.swing.JTextField textEmployeeSuburb;
    private javax.swing.JTextField textFindPersonne;
    private javax.swing.JTextField textNameTable;
    private javax.swing.JTextField textNomBdD;
    private javax.swing.JEditorPane textRequeteSQL;
    private javax.swing.JTextField textState;
    // End of variables declaration//GEN-END:variables
}
